using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;
using UnityEngine;
using HammerAndSickle.Models;
using HammerAndSickle.Controllers;
using HammerAndSickle.Services;
using HammerAndSickle.Core.GameData;

namespace HammerAndSickle.Helpers
{
    /// <summary>
    /// A flat data representation of a combat unit for serialization to/from OOB files.
    /// Compatible with the Scenario Editor's JSON output format, where weapon profile IDs
    /// are serialized as strings (e.g., "INF_REG_SV") rather than integer enum values.
    /// </summary>
    [Serializable]
    public class OobUnitData
    {
        public string UnitID { get; set; }
        public string UnitName { get; set; }
        public float MapPosX { get; set; }
        public float MapPosY { get; set; }
        public int Side { get; set; }
        public int Nationality { get; set; }
        public int Classification { get; set; }
        public int Role { get; set; }
        public int IntelProfileType { get; set; }

        // String-based weapon profile IDs from the Scenario Editor
        public string DeployedProfileID { get; set; }
        public string MobileProfileID { get; set; }
        public string EmbarkedProfileID { get; set; }

        public bool IsMountable { get; set; }
        public bool IsEmbarkable { get; set; }
        public int Experience { get; set; }
        public int Efficiency { get; set; }
        public int Deployment { get; set; }
        public int Spotted { get; set; }
        public float ICM { get; set; }
        public float HitPoints { get; set; }
        public float DaysSupply { get; set; }
        public int DepotCategory { get; set; }
        public int DepotSize { get; set; }
        public List<string> AttachedAirUnitIDs { get; set; } = new List<string>();
    }

    /// <summary>
    /// Static helper for loading OOB (Order of Battle) files generated by the Scenario Editor.
    ///
    /// The Scenario Editor outputs JSON arrays where:
    ///   - Enum fields (Side, Nationality, Classification, etc.) are serialized as integers
    ///   - WeaponType profile fields (DeployedProfileID, MobileProfileID, EmbarkedProfileID)
    ///     are serialized as strings matching the WeaponType enum name (e.g., "INF_REG_SV")
    ///   - AttachedAirUnitIDs contains string unit IDs for fixed-wing aircraft assigned to airbases
    ///   - HitPoints and DaysSupply are stored as 0.0–1.0 ratios
    /// </summary>
    public static class OOBFileLoader
    {
        #region Private Fields

        private const string CLASS_NAME = nameof(OOBFileLoader);
        private readonly static bool _debug = false;

        // Cache for WeaponType string-to-enum lookup
        private static Dictionary<string, WeaponType> _weaponTypeLookup;

        #endregion // Private Fields

        #region Public Methods

        /// <summary>
        /// Loads a standalone OOB file from the user's Documents folder.
        /// Clears existing units and registers loaded units with GameDataManager.
        /// </summary>
        /// <param name="filename">Filename with or without .oob extension</param>
        /// <returns>True if load succeeded, false otherwise</returns>
        public static bool LoadStandaloneOob(string filename)
        {
            if (_debug)
                Debug.Log($"{CLASS_NAME}.{nameof(LoadStandaloneOob)}: Loading standalone OOB file: {filename}");

            string filePath = BuildFilePath(filename, AppService.OobPath);
            return LoadOobFile(filePath, "standalone");
        }

        /// <summary>
        /// Loads a campaign OOB file from the generated data folder.
        /// Clears existing units and registers loaded units with GameDataManager.
        /// </summary>
        /// <param name="filename">Filename with or without .oob extension</param>
        /// <returns>True if load succeeded, false otherwise</returns>
        public static bool LoadCampaignOob(string filename)
        {
            if (_debug)
                Debug.Log($"{CLASS_NAME}.{nameof(LoadCampaignOob)}: Loading campaign OOB file: {filename}");

            string filePath = BuildFilePath(filename, AppService.GDP_OobPath);
            return LoadOobFile(filePath, "campaign");
        }

        #endregion // Public Methods

        #region Private Methods

        /// <summary>
        /// Builds the full file path from filename and base directory.
        /// Handles both "xxx.oob" and "xxx" formats.
        /// </summary>
        private static string BuildFilePath(string filename, string basePath)
        {
            if (string.IsNullOrEmpty(filename))
            {
                throw new ArgumentException("Filename cannot be null or empty", nameof(filename));
            }

            // Handle both "xxx.oob" and "xxx" formats
            string cleanFilename = filename.EndsWith(".oob", StringComparison.OrdinalIgnoreCase)
                ? filename
                : $"{filename}.oob";

            string fullPath = Path.Combine(basePath, cleanFilename);

            if (_debug)
                Debug.Log($"{CLASS_NAME}.{nameof(BuildFilePath)}: Built path: {fullPath}");

            return fullPath;
        }

        /// <summary>
        /// Initializes the WeaponType string-to-enum lookup dictionary on first use.
        /// Maps enum member names (e.g., "INF_REG_SV") to their WeaponType enum values.
        /// </summary>
        private static void EnsureWeaponTypeLookup()
        {
            if (_weaponTypeLookup != null)
                return;

            _weaponTypeLookup = new Dictionary<string, WeaponType>(StringComparer.OrdinalIgnoreCase);
            foreach (WeaponType wt in Enum.GetValues(typeof(WeaponType)))
            {
                _weaponTypeLookup[wt.ToString()] = wt;
            }

            if (_debug)
                Debug.Log($"{CLASS_NAME}.{nameof(EnsureWeaponTypeLookup)}: Built lookup with {_weaponTypeLookup.Count} entries");
        }

        /// <summary>
        /// Resolves a string-based weapon profile ID to its WeaponType enum value.
        /// Returns WeaponType.NONE for null, empty, or "NONE" inputs.
        /// </summary>
        /// <param name="profileId">String weapon type name from the Scenario Editor JSON</param>
        /// <returns>Corresponding WeaponType enum value</returns>
        private static WeaponType ResolveWeaponType(string profileId)
        {
            if (string.IsNullOrEmpty(profileId) || profileId == "NONE")
                return WeaponType.NONE;

            EnsureWeaponTypeLookup();

            if (_weaponTypeLookup.TryGetValue(profileId, out WeaponType result))
                return result;

            Debug.LogWarning($"{CLASS_NAME}.{nameof(ResolveWeaponType)}: Unknown weapon type string: '{profileId}', defaulting to NONE");
            return WeaponType.NONE;
        }

        /// <summary>
        /// Core loading logic for OOB files produced by the Scenario Editor.
        ///
        /// Processing order:
        ///   1. Read and validate JSON file
        ///   2. Deserialize into OobUnitData list (string-based profile IDs)
        ///   3. Clear existing game state
        ///   4. First pass: Create all CombatUnit instances with resolved WeaponType enums
        ///   5. Second pass: Restore air unit attachments between airbases and fixed-wing units
        /// </summary>
        /// <returns>True if load succeeded, false otherwise</returns>
        private static bool LoadOobFile(string filePath, string sourceType)
        {
            try
            {
                if (_debug)
                    Debug.Log($"{CLASS_NAME}.{nameof(LoadOobFile)}: Starting load from {sourceType} path: {filePath}");

                // Validate file exists
                if (!File.Exists(filePath))
                {
                    string errorMsg = $"OOB file not found: {filePath}";
                    AppService.CaptureUiMessage(errorMsg);
                    throw new FileNotFoundException(errorMsg, filePath);
                }

                // Read JSON content
                string jsonContent = File.ReadAllText(filePath);
                if (string.IsNullOrEmpty(jsonContent))
                {
                    string errorMsg = $"OOB file is empty: {filePath}";
                    AppService.CaptureUiMessage(errorMsg);
                    throw new InvalidDataException(errorMsg);
                }

                if (_debug)
                    Debug.Log($"{CLASS_NAME}.{nameof(LoadOobFile)}: Read {jsonContent.Length} characters from file");

                // Deserialize OOB data — uses string-based profile IDs from Scenario Editor
                var options = new JsonSerializerOptions
                {
                    WriteIndented = true,
                    PropertyNameCaseInsensitive = true
                };

                var oobDataList = JsonSerializer.Deserialize<List<OobUnitData>>(jsonContent, options);

                if (oobDataList == null || oobDataList.Count == 0)
                {
                    string errorMsg = $"No units found in OOB file: {filePath}";
                    AppService.CaptureUiMessage(errorMsg);
                    throw new InvalidDataException(errorMsg);
                }

                if (_debug)
                    Debug.Log($"{CLASS_NAME}.{nameof(LoadOobFile)}: Deserialized {oobDataList.Count} unit entries");

                // Clear existing game state
                if (_debug)
                    Debug.Log($"{CLASS_NAME}.{nameof(LoadOobFile)}: Clearing existing game state");

                GameDataManager.Instance.ClearAll();

                // First pass: Create all units from OOB data
                var unitMap = new Dictionary<string, CombatUnit>();
                int playerCount = 0;
                int aiCount = 0;
                int resolveWarnings = 0;

                foreach (var data in oobDataList)
                {
                    if (_debug)
                        Debug.Log($"{CLASS_NAME}.{nameof(LoadOobFile)}: Creating unit: {data.UnitName} (ID: {data.UnitID})");

                    // Resolve string-based weapon profile IDs to WeaponType enum values
                    WeaponType deployedProfile = ResolveWeaponType(data.DeployedProfileID);
                    WeaponType mobileProfile = ResolveWeaponType(data.MobileProfileID);
                    WeaponType embarkedProfile = ResolveWeaponType(data.EmbarkedProfileID);

                    if (deployedProfile == WeaponType.NONE && !string.IsNullOrEmpty(data.DeployedProfileID) && data.DeployedProfileID != "NONE")
                    {
                        Debug.LogWarning($"{CLASS_NAME}.{nameof(LoadOobFile)}: Could not resolve deployed profile '{data.DeployedProfileID}' for unit {data.UnitName}");
                        resolveWarnings++;
                    }

                    // Cast integer enum fields to their proper types
                    var side = (Side)data.Side;
                    var nationality = (Nationality)data.Nationality;
                    var classification = (UnitClassification)data.Classification;
                    var role = (UnitRole)data.Role;
                    var profileType = (RegimentProfileType)data.IntelProfileType;
                    var depotCategory = (DepotCategory)data.DepotCategory;
                    var depotSize = (DepotSize)data.DepotSize;

                    // Create unit with full constructor
                    var unit = new CombatUnit(
                        data.UnitName,
                        classification,
                        role,
                        side,
                        nationality,
                        profileType,
                        deployedProfile,
                        data.IsMountable,
                        mobileProfile,
                        data.IsEmbarkable,
                        embarkedProfile,
                        depotCategory,
                        depotSize
                    );

                    // Apply saved state
                    unit.SetUnitID(data.UnitID);
                    unit.SetPosition(new Position2D(data.MapPosX, data.MapPosY));
                    unit.SetExperienceLevel((ExperienceLevel)data.Experience);
                    unit.SetEfficiencyLevel((EfficiencyLevel)data.Efficiency);
                    unit.SetDeploymentPosition((DeploymentPosition)data.Deployment);
                    unit.SetSpottedLevel((SpottedLevel)data.Spotted);
                    unit.SetICM(data.ICM);
                    unit.HitPoints.SetCurrent(unit.HitPoints.Max * data.HitPoints);
                    unit.DaysSupply.SetCurrent(unit.DaysSupply.Max * data.DaysSupply);

                    // Track for second pass
                    unitMap[unit.UnitID] = unit;

                    // Register with GameDataManager
                    if (GameDataManager.Instance.RegisterCombatUnit(unit))
                    {
                        if (unit.Side == Side.Player)
                            playerCount++;
                        else
                            aiCount++;

                        if (_debug)
                            Debug.Log($"{CLASS_NAME}.{nameof(LoadOobFile)}: Registered unit: {unit.UnitName} ({unit.Side})");
                    }
                    else
                    {
                        Debug.LogWarning($"{CLASS_NAME}.{nameof(LoadOobFile)}: Failed to register unit: {unit.UnitName}");
                    }
                }

                if (_debug)
                    Debug.Log($"{CLASS_NAME}.{nameof(LoadOobFile)}: First pass complete. Created {unitMap.Count} units ({resolveWarnings} profile resolve warnings)");

                // Second pass: Restore air unit attachments
                int attachmentCount = 0;
                foreach (var data in oobDataList.Where(d => d.AttachedAirUnitIDs != null && d.AttachedAirUnitIDs.Count > 0))
                {
                    if (unitMap.TryGetValue(data.UnitID, out var airbase))
                    {
                        if (_debug)
                            Debug.Log($"{CLASS_NAME}.{nameof(LoadOobFile)}: Restoring air attachments for: {airbase.UnitName}");

                        foreach (var airUnitId in data.AttachedAirUnitIDs)
                        {
                            if (unitMap.TryGetValue(airUnitId, out var airUnit))
                            {
                                if (airbase.AddAirUnit(airUnit))
                                {
                                    attachmentCount++;
                                    if (_debug)
                                        Debug.Log($"{CLASS_NAME}.{nameof(LoadOobFile)}: Attached {airUnit.UnitName} to {airbase.UnitName}");
                                }
                            }
                            else
                            {
                                Debug.LogWarning($"{CLASS_NAME}.{nameof(LoadOobFile)}: Air unit ID not found: {airUnitId}");
                            }
                        }
                    }
                }

                if (_debug && attachmentCount > 0)
                    Debug.Log($"{CLASS_NAME}.{nameof(LoadOobFile)}: Second pass complete. Restored {attachmentCount} air unit attachments");

                // Success message
                int totalUnits = playerCount + aiCount;
                string successMsg = $"Loaded {totalUnits} units (Player: {playerCount}, AI: {aiCount}) from {sourceType} OOB: {Path.GetFileName(filePath)}";

                if (resolveWarnings > 0)
                    successMsg += $" ({resolveWarnings} profile warnings)";

                AppService.CaptureUiMessage(successMsg);

                if (_debug)
                    Debug.Log($"{CLASS_NAME}.{nameof(LoadOobFile)}: {successMsg}");

                return true;
            }
            catch (Exception e)
            {
                string errorMsg = $"Failed to load OOB file: {Path.GetFileName(filePath)}";
                AppService.HandleException(CLASS_NAME, nameof(LoadOobFile), e);
                AppService.CaptureUiMessage(errorMsg);
                return false;
            }
        }

        #endregion // Private Methods
    }
}
